### ISSUE TITLE
[Bug Report] group match

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [Bowen7/regex-vis#103]
[reproduction](https://regex-vis.com/?r=%5E%28mask%7Cbg%7Cauto%29%24)
focus on the `mask` keyword match

![image](https://github.com/Bowen7/regex-vis/assets/54026110/87b7f078-96b8-496d-a5ef-7ea392750720)

after toggle `include escape '\'`

![image](https://github.com/Bowen7/regex-vis/assets/54026110/f5d87ec3-2950-4e73-b3d0-55697492fe35)

**Comment by Bowen7** [comment]
I'm sorry, but I clicked on the link and didn't find any issues.

Can you please explain it in more detail? Thank you.

**Comment by Lmmmmmm-bb** [comment]
I am really sorry. After I re-confirmed it was the issue caused by the Chrome extension. 😂

regex-vis is an amazing regex tool. Thank you for your fantastic work!

**Comment by Bowen7** [comment]
> I am really sorry. After I re-confirmed it was the issue caused by the Chrome extension. 😂
> 
> regex-vis is an amazing regex tool. Thank you for your fantastic work!

Could you tell me what extension it is? I'm just curious about this.

**Comment by Lmmmmmm-bb** [comment]
Of course. The extension is _Relingo_ which helps me to read the document in English. I have just installed the past few days.

Normally, it shows by this.

![image](https://github.com/Bowen7/regex-vis/assets/54026110/306b6e81-6317-44de-8d6c-cab8fc3488ed)

So this left parenthesis is _Relingo_ insert it, but at first I didn't realize it.

![image](https://github.com/Bowen7/regex-vis/assets/54026110/ba7ff2ff-d0c2-4db2-85eb-0933d050e3a8)
