### ISSUE TITLE
Can't click or drag elements from RHS legends onto main panel

### ISSUE THREAD

**Issue by NathanBillington** [Bowen7/regex-vis#125]
Have tested using Windows 11 Chrome (v 124.0.6367.61) and also Firefox (v 125.0.2).

Can't click or drag elements from the RHS Legend onto the main panel to create the REGEX.

It's not throwing any errors in the console.

**Comment by Bowen7** [comment]
The legends simply help users understand the graph, so you cannot click or drag them.

**Comment by NathanBillington** [comment]
![image](https://github.com/Bowen7/regex-vis/assets/11265274/a85c8661-1d14-4e3a-b64d-dec337435c90)

This might be a bit misleading then.. :)

**Comment by Bowen7** [comment]
Oh, sorry for that. This means you can click/drag the graphic on the left(I added a left arrow). Perhaps I should move this tip to another place. :)
