### ISSUE TITLE
无法本地启动服务

### ISSUE THREAD

**Issue by zhangxianglink** [Bowen7/regex-vis#126]
**我想要部署项目到本地。**
按照文档里面 node16 版本pnpm install / start , 提示当前版本需要18，
![image](https://github.com/Bowen7/regex-vis/assets/39996077/12497be2-da2a-4c67-9e48-72080063c164)
node  v18.20.4
npm 10.8.1
os window  
当我用上面的版本操作，截图报错jest
![image](https://github.com/Bowen7/regex-vis/assets/39996077/47d6d12a-9a3e-4241-83a1-d35764e62685)
然后我删除了package.json中的jest部分， 然后删除package.lock.yml
pnpm start 报错加密问题因为升级node18导致的
我用这个命令解决了，$env:NODE_OPTIONS="--openssl-legacy-provider"
![image](https://github.com/Bowen7/regex-vis/assets/39996077/85ec510c-994f-4e1d-a216-dd804279ab9c)
但是最后报typescript 版本5.5.3 过高，我实在是想不到方法了
![image](https://github.com/Bowen7/regex-vis/assets/39996077/b3963d65-1d7a-4f33-bc56-6a19ec65eafd)

希望能出一个部署教程，方便一下非前端开发人员使用，感谢

**Comment by Bowen7** [comment]
I will take a look tonight. Thanks for your report.

**Comment by Bowen7** [comment]
BTW, may I ask what your purpose is to host it, why not use regex-vis.com instead?

How about I provide a Vercel Deploy Button to README.md?

**Comment by Bowen7** [comment]
It seems I should upgrade `create-react-app` to version 5. However, `create-react-app` is not currently under active maintenance. I have decided to migrate to Vite. Maybe this weekend.

**Comment by zhangxianglink** [comment]
> BTW, may I ask what your purpose is to host it, why not use regex-vis.com instead?
> 
> If you want to deploy this project, how about I provide a Vercel Deploy Button to README.md?

Thank you for your reply. I find this project very interesting and would like to debug it locally.

**Comment by Bowen7** [comment]
Thank you! You can track the process in this [PR](https://github.com/Bowen7/regex-vis/pull/127)

**Comment by Bowen7** [comment]
I believe this issue is fixed at https://github.com/Bowen7/regex-vis/pull/127. Feel free to reopen the issue if you still cannot run the app
