### ISSUE TITLE
error occurs when executing "pnpm install"

### ISSUE THREAD

**Issue by Staceycgc** [Bowen7/regex-vis#28]
@Bowen7 
when I execute "pnpm install", an error occurs. The error can be described as follows:
```bash
............  

Progress: resolved 1787, reused 0, downloaded 1571, added 1785  
Progress: resolved 1787, reused 0, downloaded 1571, added 1786  
TypeError: Cannot set property name of  which has only a getter  
    at err (/usr/local/node-v14.19.1-linux-x64/lib/node_modules/pnpm/dist/pnpm.cjs:12443:20)  
    at runPnpm (/usr/local/node-v14.19.1-linux-x64/lib/node_modules/pnpm/dist/pnpm.cjs:182389:5)  
    at runMicrotasks (<anonymous>)  
    at processTicksAndRejections (internal/process/task_queues.js:95:5)  
    at async /usr/local/node-v14.19.1-linux-x64/lib/node_modules/pnpm/dist/pnpm.cjs:182379:7  
```
I wonder what I did wrong during the installation. Thanks a lot!

**Comment by Bowen7** [comment]
I'm not sure why.
Maybe you can have a look: https://github.com/pnpm/pnpm/issues/4270

**Comment by Staceycgc** [comment]
I found the reason that the error occurs. I set a local dns host for "codeload.github.com", but one of the packages that  "pnpm install" resolved was from "codeload.github.com".  The tips are as follows：
```bash

 WARN  GET https://codeload.github.com/Bowen7/hast-util-to-babel-ast/tar.gz/29729bd53973ea51eb86a8fcc1ddc1651ce51013 error (ECONNREFUSED). Will retry in 10 seconds. 2 retries left.
```
As a result, I failed to get that package, and the execution of "pnpm install" failed as well.
Thanks again for your answer!
