### ISSUE TITLE
Error (`/`): Invalid regular expression

### ISSUE THREAD

**Issue by Andiedie** [Bowen7/regex-vis#29]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/21376471/159862908-46bb2544-43f3-4549-8975-b1a177882756.png">

**Comment by Bowen7** [comment]
`/` should be escaped by `\`.

**Comment by Andiedie** [comment]
> `/` should be escaped by `\`.

`/` is actually a valid RegExp
<img width="151" alt="image" src="https://user-images.githubusercontent.com/21376471/160093192-2aac231b-e300-49c4-abcd-c607021d71f4.png">

Only when you write it literally is JavaScript like '/\//', it should be escaped.
But there's not hint on the web page that I am writing a literal JavaScript RegExp, so I don't think it's a good design to force user escape a normal symbol.

**Comment by Bowen7** [comment]
I agree with you.
I add a `Select` to switch `RegExp` and `Literal`. In `RegExp` mode, you needn't escape `\`.
[Preview url: regex-vis.vercel.app](https://regex-vis.vercel.app/)

Suggestions are welcome.
