### ISSUE TITLE
the "Test" function does not work

### ISSUE THREAD

**Issue by bingyu50** [Bowen7/regex-vis#38]
the regexp is: .+\s([a-zA-Z]+\s?)
test: DSad SDA 1123
expected: shows error (red)
actual: did not see any error for it

**Comment by Bowen7** [comment]
```js
/.+\s([a-zA-Z]+\s?)/.test('DSad SDA 1123') // true
```
When using the constructor function, the normal string escape rules (preceding special characters with \ when included in a string) are necessary:
```js
new RegExp('.+\\s([a-zA-Z]+\\s?)').test('DSad SDA 1123') //true
```

**Comment by bingyu50** [comment]
I am not sure if I express clear, what I mean here is: when I try the above regex in: https://regex-vis.com/ ,  I input the regex, then I input the test string under the top right Test tab, I hope it shows error, but it doesn’t

**Comment by Bowen7** [comment]
The test string `DSad SDA 1123` and the RegExp `.+\s([a-zA-Z]+\s?)` are matched.
<img width="346" alt="image" src="https://user-images.githubusercontent.com/27432981/166418576-3634dbf4-7025-45ea-9313-4001ad1bde50.png">
So there are no errors.

**Comment by bingyu50** [comment]
But the meaning of the regex should only match “DSad SDA ”, 1123 should not matched by the regex? Why it still shows true?

**Comment by Bowen7** [comment]
You should add an end assertion `$`.
`/.+\s([a-zA-Z]+\s?)$/.test('DSad SDA 1123')` will return `false`

**Comment by bingyu50** [comment]
Got it! Thanks!
