### ISSUE TITLE
Visual link between the visualization and the regex

### ISSUE THREAD

**Issue by RheingoldRiver** [Bowen7/regex-vis#40]
A visual link between the visualization and the regex would help to see what's going on - either (a) when you click a section of the visualization, it could highlight/bold/underline in the regex text, or perhaps (b) the different parts of the visualization could have (toggleable) persistent highlighting in the regex, similar to what regex101.com does.

**Comment by Bowen7** [comment]
Sounds good.
I'm currently refactoring my code. I will add this feature after refactoring

**Comment by MarqueIV** [comment]
Can this be added to the editor window?  And for that matter, can you make your editor window wider? I routinely deal with long regex files and they require too much scrolling.
