### ISSUE TITLE
Selection area is jumpy when mouse dragged over node

### ISSUE THREAD

**Issue by BryghtShadow** [Bowen7/regex-vis#45]
When dragging the mouse to select some nodes, there's a "jump" in the selection `<div>` when the mouse moves over the "hitbox" of `<text>` or its wrapping `<g>`, and/or perhaps the children `<tspan>`:
```svg
<g font-size="16" transform="translate(25.75,20)">
    <text class="text" dy="0" text-anchor="middle" font-size="16">
        <tspan class="quote">" </tspan><tspan>a</tspan><tspan class="quote"> "</tspan>
    </text>
</g>
```
![regex-vis](https://user-images.githubusercontent.com/1018221/175368238-3c25d6c3-37fc-4484-978f-d3926e287cc4.gif)

**Comment by Bowen7** [comment]
Thanks for reporting this.
Can you provide your OS, and browser info? I can't reproduce it.

**Comment by BryghtShadow** [comment]
Can confirm, the above link works 👍
I was using Firefox, Win 11 (forgot to check in other browsers as well as adding the browser/OS info in ticket).
