### ISSUE TITLE
/没有转义符

### ISSUE THREAD

**Issue by fu827707013** [Bowen7/regex-vis#56]
![B9D M62(DRYQ21G$FT9OVNB](https://user-images.githubusercontent.com/41055075/180930875-f7aa533f-f6c8-4a9b-a192-6ba5864be9d1.png)

/字符串生成的时候没有转义符，标准的是有的吧
![QQR~%ODQ7_OEZ QVDI@}XXH](https://user-images.githubusercontent.com/41055075/180931460-e1fde683-0539-4df4-b207-620408130e24.png)

**Comment by Bowen7** [comment]
这是在预期内的
如果表达式没有以 `//` 包裹，默认为字符串模式，即通过 `new RegExp()` 方式构建正则表达式
这种情况下 `/` 是可以不加转义符号的，执行 `new RegExp('/')` 并不会报错
如果包裹 `//` 了，则视为字面量模式，就会自动转义 `\`
