### ISSUE TITLE
[BUG] 过长的正则生成的图无法左右滑动

### ISSUE THREAD

**Issue by yinxulai** [Bowen7/regex-vis#57]
# 问题描述

- 正则太长，生成的图宽度很大，无法左右滚动查看看完整的图

## 问题截图

- ![image](https://user-images.githubusercontent.com/22045569/187654391-5e99cb87-d0d3-4637-95d1-5569f1c6ab7d.png)

## 参考正则

- `^avhls/(?<format>m3u8)(?:/segtime/(?<segtime>\d+))?(?:/ss/(?<ss>\d+)/t/(?<t>\d+))?(?:(/ab/(?<ab>\d+))|(/aq/(?<aq>\d+)))?(?:/ar/(?<ar>\d+))?(?:/r/(?<r>\d+))?(?:/vb/(?<vb>\d+))?(?:/vcodec/(?<vcodec>libx264|libvpx|libtheora|libxvid))?(?:/acodec/(?<acodec>libmp3lame|libfdk_aac))?(?:/s/(?<sWidth>\d?)x(?<sHeigth>\d?))?(?:/play/(?<play>[^/]+))?(?:/outKey/(?<outKey>[^/]))?(?:/pattern/(?<pattern>[^/]))?(?:/?)$`

**Comment by Bowen7** [comment]
Thanks for reporting it.
I forget to add a scrollbar. Because I always use a trackpad to scroll the page.
I fix it on [https://regex-vis-git-fix-scrollbar-bowen.vercel.app/](https://regex-vis-git-fix-scrollbar-bowen.vercel.app/).
