### ISSUE TITLE
can't launch the service 

### ISSUE THREAD

**Issue by allenhu12** [Bowen7/regex-vis#59]
./src/index.tsx
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer

**Comment by Bowen7** [comment]
Can you provide your OS and node version?

**Comment by allenhu12** [comment]
> 

➜  src git:(master) ➜  src git:(master) node --version
v18.2.0
➜  src git:(master) sw_vers
ProductName:    macOS
ProductVersion: 12.5.1
BuildVersion:   21G83

**Comment by Bowen7** [comment]
https://github.com/mozilla/source-map/issues/454.
You can downgrade to node 16.

**Comment by allenhu12** [comment]
yes, it works fine when node has been downgrade to version 16
