### ISSUE TITLE
Can you build it for a docker container?

### ISSUE THREAD

**Issue by HolmesZhao** [Bowen7/regex-vis#77]
Thanks~

**Comment by Bowen7** [comment]
I am not familiar with Docker. I will try it out when I have time.
Also, welcome PR.

**Comment by Bowen7** [comment]
BTW, if you use Vercel or Netlify, you can just fork this project and deploy it easily

**Comment by HolmesZhao** [comment]
> BTW, if you use Vercel or Netlify, you can just fork this project and deploy it easily

ok , thx

**Comment by Bowen7** [comment]
Here are my Vercel build and development settings:
Framework Preset: Create React App
Build Command: `npm run build`
Output Directory: `build`
Install Command: `npm i pnpm -g && pnpm i`

Node.js Version: 14.x
