### ISSUE TITLE
如何将项目引入（import）到自己的react项目中？

### ISSUE THREAD

**Issue by wangchong2023** [Bowen7/regex-vis#78]

**Comment by wangchong2023** [comment]
> 严格来说，这个项目是一个应用（Application），而不是一个库（Library），所以我没有将它发布到 npm 上。
> 
> 你想引入哪些功能？

我们在做个国产化的产品，因为当前这个支持中文对我们来说比较友好。
我们的业务功能，用户往往需要在页面上输入正则表达式，但是我们希望提供给客户看到自己正则表达式代表的范围以及验证正则表达式的能力（这个没看到界面支持）。

**Comment by Bowen7** [comment]
> 1、查看正则表达式代表范围的界面元素示意：

我考虑发布一个 npm 包，可以将正则表达式渲染成 SVG 图形：
```jsx
<RegexGraph  regex={yourRegex} />
```
但可能不会很快发布，可能跟不上你们的产品节奏

> 2、测试某个特定的值是否在正则表达式范围内的界面元素：

网页右侧第三个 Tab：Test（测试）可以进行测试。对于你的需求，我感觉可以在点击测试按钮后`new RegExp(userRegex).test(userInput)`获取是否匹配？

**Comment by wangchong2023** [comment]
> > 1、查看正则表达式代表范围的界面元素示意：
> 
> 我考虑发布一个 npm 包，可以将正则表达式渲染成 SVG 图形：
> 
> ```js
> <RegexGraph  regex={yourRegex} />
> ```
> 
> 但可能不会很快发布，可能跟不上你们的产品节奏
> 
> > 2、测试某个特定的值是否在正则表达式范围内的界面元素：
> 
> 网页右侧第三个 Tab：Test（测试）可以进行测试。对于你的需求，我感觉可以在点击测试按钮后`new RegExp(userRegex).test(userInput)`获取是否匹配？

但可能不会很快发布，可能跟不上你们的产品节奏
**-->非常感谢！在您没有发布这个npm包的时候，有啥办法集成这个项目吗？或者有集成步骤吗？**

网页右侧第三个 Tab：Test（测试）可以进行测试。对于你的需求，我感觉可以在点击测试按钮后new RegExp(userRegex).test(userInput)获取是否匹配？
**-->第3个Tab说实在话没看懂咋用，我在上面的回复中更新了从网上其它地方的示例（可能不需要那些修饰符）。我的直接使用是：1个是正则表达式，1个是待匹配内容，输出是匹配结果（可能包括是否匹配成功，匹配到的位置（可选））。**

**Comment by wangchong2023** [comment]
非常感谢！
